# TaaOS Welcome Module (Physical Override to ensure 8GB instead of 10GB)
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false

requirements:
    requiredStorage: 6
    requiredRam: 1.0
    internetCheckUrl: https://www.google.com
    check:
        - ram
        - power
        - internet
        - root
    required:
        - ram
geoip:
    style: "none"
