# TaaOS Welcome Module (Physical Override to ensure 8GB instead of 10GB)
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false

requirements:
    requiredStorage: 8
    requiredRam: 1.0
    internetCheckUrl: https://www.google.com
    check:
        - storage
        - ram
    required:
        - storage
        - ram
geoip:
    style: "none"
